### ISSUE TITLE
subcommands instead of separate commands

### ISSUE THREAD

**Issue by infokiller** [AndydeCleyre/zpy#18]
Would it make sense to make the different commands subcommands of `zpy`, while making the separate commands opt-out/opt-in?
My reasons are:

1. `zpy <subcmd>` improves discoverability of the different commands. Right now `zpy subcmd` has good autocomplete but prints the docs, so these will need to be moved to a new `help` subcommand or something (so `zpy help pypc` instead of `zpy pypc`).
2. I don't like polluting the global commands namespace, and prefer to define my own aliases for what I use most often. The current implementation forces these commands into the global namespace.

Thanks!

**Comment by AndydeCleyre** [comment]
This would mean a lot of changes, and I'm yet undecided on the issue. 

- The functions do currently call each other, but this could be partially managed by using more "internal" function names like `.zpy_unexposed_pipc`. Would you consider functions named like that to be polluting the namespace still?
- The mechanism that scans the code comments to generate help and completions would need adjustment as well.
- I wouldn't *personally* want to preface each function with a global launcher command to run it, but it could exist as an option in addition to the regular top-level functions.
- So I think I want to work on this, but it won't be done too quickly, and I'm not 100% sure. I'll create an experimental branch for it.

In the short term, are there any particular naming conflicts we might be able to mitigate the trouble with?

**Comment by AndydeCleyre** [comment]
Update: I'm making good progress in an experimental branch to allow the user to choose which functions are "exposed" via a zstyle command. Functions which are not "exposed" are still in the namespace, but named like `.zpy_ui_vrun`, `.zpy_ui_pipc`, etc.

Once that's all worked out and released, I'll have another look at the everything-as-a-subcommand task.

**Comment by infokiller** [comment]
Thanks for the very quick progress on this!

Indeed, I would not suggest removing the functions, but only renaming them with a `zpy` prefix like you did. The common convention I see in zsh is to also use underscores or dashes in the prefix, which means `_zpy-pipc`/`-zpy-pipc` for `pipc` (I guess the dash version avoids confusion with zsh completion functions), but using a dot like you did is probably fine as well.

And a zstyle option would be great, I assume it defines aliases?

**Comment by infokiller** [comment]
> In the short term, are there any particular naming conflicts we might be able to mitigate the trouble with?

I'm not aware of any conflicts, I'm just being paranoid. My other reason for this is that I like the idea of using `zpy <tab>` to both discover and *run* a command, instead of `zpy <tab>` to see discover it, and then separately running it.

**Comment by AndydeCleyre** [comment]
I need to:

- do more testing
- update docs accordingly
- do some performance profiling/fixing

but you're very welcome to try out the `feature/interface-as-subcommands` branch.

In it, you should be able to use `zpy` as the top level command with everything else as a subcommand, and the former functionality of the `zpy` function is available as `zpy help <funcname>`.

By default the individual functions are still available as top level commands, but you can hide them all except for `zpy` by putting this in your profile before the plugin is loaded:

```bash
zstyle ':zpy:*' exposed-funcs zpy
```

**Comment by infokiller** [comment]
Thanks a lot @AndydeCleyre 
Works very well. The only issue I've encountered is that `zpy pipz <args>` completion doesn't work with `zstyle ':zpy:*' exposed-funcs zpy`.

**Comment by AndydeCleyre** [comment]
Excellent, thank you! I just pushed a fix for that now (and wouldn't have noticed without your feedback).

Updating the task list for this branch before I can merge it:

- [ ] keep testing
- [ ] update docs
- [ ] profile and fix performance (probably need to re-work the help functions and their use of zstyle)
- [ ] update the container build scripts to match the new interface (`.zpy_mkbin` is renamed, for one thing)

**Comment by AndydeCleyre** [comment]
I've collapsed the feature branch back into `develop`, and will release `0.3.0` soon.

Thanks again for this push, I think this is a great improvement for the project.

**Comment by infokiller** [comment]
Thanks so much for adding this!
